language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge
  allow_failures:
    - php: hhvm

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
  - phpunit
